  -- The schema column names are included here for you.
  -- Your task is to add the appropriate data type to each field.
CREATE TABLE crimes (
  analysis_neighborhood,
  cad_number,
  cnn,
  filed_online,
  incident_category,
  incident_code,
  incident_date,
  incident_datetime,
  incident_day_of_week,
  incident_description,
  incident_id,
  incident_number,
  incident_subcategory,
  incident_time,
  incident_year,
  intersection,
  latitude,
  longitude,
  point,
  police_district,
  report_datetime,
  report_type_code,
  report_type_description,
  resolution,
  row_id,
  supervisor_district
);
